version: "2"
services:
  nodeserver:
    container_name: vlepalud_node
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./node:/home/node/app
    ports:
      - "10000:3000"
    command: npm start